# Generated by Django 5.2.5 on 2025-08-22 06:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998[0-9]{9}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('education_level', models.CharField(choices=[('school', 'Maktab'), ('college', 'Kollej'), ('university', 'Universitet'), ('graduated', 'Bitirgan'), ('working', 'Ishlaydigan')], max_length=20, verbose_name="Ta'lim darajasi")),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='Maktab/Universitet nomi')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Ota-ona ismi')),
                ('parent_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998[0-9]{9}$')], verbose_name='Ota-ona telefoni')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('graduated', 'Bitirgan'), ('dropped', 'Tashlab ketgan')], default='active', max_length=20, verbose_name='Holati')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Ro'yxatga olingan sana")),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('photo', models.ImageField(blank=True, upload_to='students/photos/', verbose_name='Rasm')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy qarz')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name="Oxirgi to'lov sanasi")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_main_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('passport', 'Pasport'), ('birth_certificate', "Tug'ilganlik haqidagi guvohnoma"), ('diploma', 'Diplom'), ('certificate', 'Sertifikat'), ('photo', 'Rasm'), ('other', 'Boshqa')], max_length=20, verbose_name='Hujjat turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='students/documents/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Talaba')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talaba hujjati',
                'verbose_name_plural': 'Talaba hujjatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note_type', models.CharField(choices=[('general', 'Umumiy'), ('academic', 'Akademik'), ('behavioral', 'Xulq-atvor'), ('attendance', 'Davomat'), ('payment', "To'lov")], default='general', max_length=20, verbose_name='Eslatma turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('is_important', models.BooleanField(default=False, verbose_name='Muhim')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes_authored', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes_all', to='students.student', verbose_name='Talaba')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talaba eslatmasi',
                'verbose_name_plural': 'Talaba eslatmalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Ro'yxatga olingan sana")),
                ('start_date', models.DateField(verbose_name='Boshlangan sana')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugagan sana')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Tugallangan'), ('dropped', 'Tashlab ketgan'), ('suspended', 'Toxtatilgan')], default='active', max_length=20, verbose_name='Holati')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Jarayon foizi')),
                ('grade', models.CharField(blank=True, max_length=5, verbose_name='Baho')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='courses.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Talaba')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Talaba ro'yxati",
                'verbose_name_plural': "Talabalar ro'yxati",
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
