# Generated by Django 5.2.5 on 2025-08-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text="Maksimal o'quvchilar soni")),
                ('location', models.CharField(blank=True, help_text='Xona joylashuvi', max_length=200)),
                ('equipment', models.TextField(blank=True, help_text='Xona jihozlari')),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar")),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms_room',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='Booking maqsadi', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='groups.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Bookings',
                'db_table': 'rooms_booking',
                'ordering': ['date', 'start_time'],
                'unique_together': {('room', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
