# Generated by Django 5.2.5 on 2025-08-22 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text="Oylik to'lov miqdori (so'm)", max_digits=10)),
                ('duration_months', models.PositiveIntegerField(help_text='Kurs davomiyligi (oy)')),
                ('max_students', models.PositiveIntegerField(default=15, help_text="Maksimal o'quvchilar soni")),
                ('prerequisites', models.TextField(blank=True, help_text='Kursga kirish uchun talablar')),
                ('objectives', models.TextField(blank=True, help_text='Kurs maqsadlari')),
                ('syllabus', models.TextField(blank=True, help_text="O'quv dasturi")),
                ('certificate_template', models.FileField(blank=True, help_text='Sertifikat shabloni', null=True, upload_to='courses/certificates/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses_course',
                'ordering': ['title'],
            },
        ),
    ]
