# Generated by Django 5.2.5 on 2025-08-22 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar")),
            ],
            options={
                'verbose_name': 'Group Student',
                'verbose_name_plural': 'Group Students',
                'db_table': 'groups_student',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('planning', 'Rejalashtirilmoqda'), ('active', 'Faol'), ('completed', 'Yakunlangan'), ('archived', 'Arxivlangan'), ('cancelled', 'Bekor qilingan')], default='planning', max_length=20)),
                ('planned_start', models.DateField(help_text='Rejalashtirilgan boshlanish sanasi')),
                ('planned_end', models.DateField(help_text='Rejalashtirilgan tugash sanasi')),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('max_students', models.PositiveIntegerField(help_text="Maksimal o'quvchilar soni")),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups_group',
                'ordering': ['-created_at'],
            },
        ),
    ]
